### ISSUE TITLE
bert_config.json

### ISSUE THREAD

**Issue by AcRush420** [typebert/typebert#2]
Dear Dr. Jesse
when I run this command 
`python run_classifier.py --mode='predict' --input_meta_data_path=/data2/typebertv2_data/meta_data --train_data_path=/data2/typebertv2_data/train.tf_record --eval_data_path=/data2/typebertv2_data/test.tf_record --bert_config_file=/home/myhome/TypeBert/type-bert/bert_config.json --predict_checkpoint_path=/home/myhome/typebert_my_model/ckpt-272457 --train_batch_size=32 --eval_batch_size=32  --model_dir=/home/myhome/typebert_my_model/ --distribution_strategy=multi_worker_mirrored`

I found that there was no bert_config.json file in your git repository.
Could you plz help me figure this out? Thanks a lot.

**Comment by viktorbrech** [comment]
I have the same issue. Please add a suitable bert_config.json file. Thank you!

**Comment by kevinjesse** [comment]
Hi! something like this should suffice. Copy and paste and name _bert_config.json_. Type vocab is 40001 per _labels.txt_, and 16000 subtokens from _ts_sp.vocab_. 

**bert_config.json**
{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "max_position_embeddings": 256,
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "type_vocab_size": 2,
  "vocab_size": 16000
}

--
This repo is due for a migration to Huggingface and I will try to update it when I can. I would recommend checking out [ManyTypes4TypeScript](https://huggingface.co/datasets/kevinjesse/ManyTypes4TypeScript) while I migrate the model. The updated version, ManyTypes4TypeScript, includes versions trained from [GraphCodeBert](https://huggingface.co/kevinjesse/graphcodebert-MT4TS) and other new models.

**Comment by kevinjesse** [comment]
@AcRush420 @viktorbrech Checkout the commit 266e6700eba21bc5b8d89e221fde251c5b957dff where I uploaded a pytorch huggingface model and scripts. It has the original dataset and tokenizer too. Cheers ~
