### ISSUE TITLE
Question about predicting the type of a single JavaScript file

### ISSUE THREAD

**Issue by ShenaoW** [typebert/typebert#3]
Can I use the pre-trained typebert model on Hugging Face for infering the type of a single JavaScript file? I attempted to implement the **predict_single_file** function myself, but the predictions seem a bit strange. Could you provide a test script for inferring types from a single JavaScript file, or point out any errors in my implementation? Thank you very much for your assistance.

Here is the code snippet where I tried to implement **predict_single_file**:

```
def predict_single_file(args):

    with open("huggingface/test.js", "r") as file:
        javascript_code = file.read()

    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer_name, use_fast=True)
    model = AutoModelForTokenClassification.from_pretrained(args.checkpoint_path, num_labels=len(label_list))

    tokenized_input = tokenizer(javascript_code, padding='max_length', truncation=True, max_length=256, return_tensors="pt")
    print(tokenized_input)
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenized_input = tokenized_input.to(device)

    with torch.no_grad():
        outputs = model(tokenized_input['input_ids'], labels=None)
        predictions = outputs.logits.argmax(dim=-1)
        print(predictions)
        predicted_labels = [label_list[p] for p in predictions[0]]
        print(predicted_labels)

    return predicted_labels
```

**Comment by kevinjesse** [comment]
@ShenaoW I uploaded some code in [demo](https://github.com/typebert/typebert/tree/main/huggingface/demo) to show you how to use the [Huggingface](https://huggingface.co/kevinjesse/typebert) model with an javascript example. Remember that the model is fine-tuned with the first subtoken as labeled. So in the attached screenshot of example.js, only "**my**" in `myClass` will have the type annotation. All other subtokens that are not trained with a type annotation will not have a meaningful annotation. Of course there are many ways to improve this for practical use, however, this is a common practice in sequence tagging when using **sub**tokens. See the screenshot below.
<img width="898" alt="typebert_label_screenshot" src="https://github.com/typebert/typebert/assets/7388187/4ce65fd1-07a3-4459-be2d-d156600c7c40">
